/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: (typeof import('./src/components/TabBar copy/index.vue'))['default']
    HelloWorld: (typeof import('./src/components/HelloWorld.vue'))['default']
    NavBar: (typeof import('./src/components/NavBar/index.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    TabBar: (typeof import('./src/components/TabBar/index.vue'))['default']
    VanButton: (typeof import('vant/es'))['Button']
    VanNavBar: (typeof import('vant/es'))['NavBar']
    VanTabbar: (typeof import('vant/es'))['Tabbar']
    VanTabbarItem: (typeof import('vant/es'))['TabbarItem']
  }
}
